---
# Connect to backend collins instance
collins:
  host: http://192.168.2.4:9000
  user: robot
  pass: 42242I8KaG7V 

# configuration needed for loading in genesis
# configuration needed for tasks should all
# be kept in conf_url.
genesis:
  initrd_img_url: http://192.168.2.4:8080/genesis/image/genesis-initrd.img
  vmlinuz_url: http://192.168.2.4:8080/genesis/image/genesis-vmlinuz
  conf_url: http://192.168.2.4:8080/genesis/config.yml

vault:
  host: http://localhost:8200
  role: auth/approle/role

provisioning:
  site: unknown
  domain: local.m

  profiles:
    devnode:
      os: xenial
