---
# Connect to backend collins instance
collins:
  host: http://collins.m:9000
  user: robot
  pass: 42242I8KaG7V 

# configuration needed for loading in genesis
# configuration needed for tasks should all
# be kept in conf_url.
genesis:
  initrd_img_url: http://10.0.0.5:8080/genesis/image/genesis-initrd.img
  vmlinuz_url: http://10.0.0.5:8080/genesis/image/genesis-vmlinuz
  conf_url: http://10.0.0.5:8080/genesis/config.yml

provisioning:
  site: unknown
  domain: local.m

  profiles:
    devnode:
      os: xenial
